import { addDays, todayKey } from "../lib/date";
import type { TrackerState } from "../lib/types";

const today = todayKey();

export const demoTrackerState: TrackerState = {
  topics: [
    {
      id: "topic-healthy-eating",
      name: "Healthy Eating",
      description: "Whole foods, less processed sugar, better lunch decisions.",
      color: "#3f8f68",
      startDate: addDays(today, -45),
      endDate: null,
      archivedAt: null,
      recurrence: { type: "daily" },
      createdAt: addDays(today, -45),
      updatedAt: today,
    },
    {
      id: "topic-exercise",
      name: "Exercise",
      description: "Strength or cardio training on focused weekdays.",
      color: "#2269c8",
      startDate: addDays(today, -60),
      endDate: null,
      archivedAt: null,
      recurrence: { type: "selectedWeekdays", weekdays: [1, 3, 5] },
      createdAt: addDays(today, -60),
      updatedAt: today,
    },
    {
      id: "topic-reading",
      name: "Reading",
      description: "Read at least 20 minutes every two days.",
      color: "#8f5bd3",
      startDate: addDays(today, -40),
      endDate: null,
      archivedAt: null,
      recurrence: { type: "everyXDays", interval: 2 },
      createdAt: addDays(today, -40),
      updatedAt: today,
    },
    {
      id: "topic-sleep",
      name: "Sleep 8h",
      description: "Maintain consistent bedtime and full recovery.",
      color: "#d97706",
      startDate: addDays(today, -30),
      endDate: null,
      archivedAt: null,
      recurrence: { type: "weekly", dayOfWeek: 0 },
      createdAt: addDays(today, -30),
      updatedAt: today,
    },
    {
      id: "topic-deep-work",
      name: "Deep Work",
      description: "Long-form focus block every 2 weeks.",
      color: "#9f1239",
      startDate: addDays(today, -70),
      endDate: null,
      archivedAt: null,
      recurrence: { type: "custom", interval: 2, unit: "week", dayOfWeek: 2 },
      createdAt: addDays(today, -70),
      updatedAt: today,
    },
    {
      id: "topic-finance",
      name: "Monthly Review",
      description: "Money review and planning on the 3rd of each month.",
      color: "#0f766e",
      startDate: addDays(today, -90),
      endDate: null,
      archivedAt: null,
      recurrence: { type: "monthly", dayOfMonth: 3 },
      createdAt: addDays(today, -90),
      updatedAt: today,
    },
  ],
  entries: [
    {
      id: "entry-healthy-eating-yesterday",
      topicId: "topic-healthy-eating",
      date: addDays(today, -1),
      value: 100,
      note: "Meal prepped and skipped late snacking.",
      createdAt: addDays(today, -1),
      updatedAt: addDays(today, -1),
    },
    {
      id: "entry-healthy-eating-2",
      topicId: "topic-healthy-eating",
      date: addDays(today, -2),
      value: 65,
      note: "Good breakfast, rough dinner.",
      createdAt: addDays(today, -2),
      updatedAt: addDays(today, -2),
    },
    {
      id: "entry-exercise-1",
      topicId: "topic-exercise",
      date: addDays(today, -2),
      value: 100,
      note: "45 minute run.",
      createdAt: addDays(today, -2),
      updatedAt: addDays(today, -2),
    },
    {
      id: "entry-reading-1",
      topicId: "topic-reading",
      date: addDays(today, -4),
      value: 80,
      note: "Finished three chapters.",
      createdAt: addDays(today, -4),
      updatedAt: addDays(today, -4),
    },
    {
      id: "entry-sleep-1",
      topicId: "topic-sleep",
      date: addDays(today, -5),
      value: 0,
      note: "Travel day disrupted bedtime.",
      createdAt: addDays(today, -5),
      updatedAt: addDays(today, -5),
    },
  ],
};
